### ISSUE TITLE
TypeError: get_json_segments() got an unexpected keyword argument 'limit'

### ISSUE THREAD

**Issue by xiao11lam** [podcast-ai/podcast-ai-lab#18]
Hey, this was the issue. I met when I just want to run the demo app, I already can run the front end demo, but when I send the query to the frontend, and to see what's the response. I only get the an error like this:
```
TypeError: get_json_segments() got an unexpected keyword argument 'limit'
```
Is this is the error from the server overload or another issue? Here are the screenshots:
![image](https://user-images.githubusercontent.com/58770171/178234247-978c049c-430d-44a3-b7d5-4056148442cc.png)
Also, here is the terminal log:
![image](https://user-images.githubusercontent.com/58770171/178234424-0a3ec8d5-c41e-4304-ae59-2e0e47c78bf7.png)

**Comment by clstaudt** [comment]
@xiao11lam  I pushed a quick fix, please test and close the issue if working.

**Comment by xiao11lam** [comment]
@clstaudt I already tried the latest code there, but the error is still there.

**Comment by clstaudt** [comment]
@xiao11lam  I believe that I pushed new code so that the error cannot be the same. Can you check again?

**Comment by xiao11lam** [comment]
Yes, @clstaudt thats true, just need to have those podcasts files I suppose.
![image](https://user-images.githubusercontent.com/58770171/178715016-762a47c5-de71-4b3c-a339-c598d413bc47.png)

**Comment by clstaudt** [comment]
1. Download the podcast with podcast-downloader (example configuration file in /config)
2. place in /data/podcasts
